### ISSUE TITLE
Newline character doesn't work in cmus_notify.sh

### ISSUE THREAD

**Issue by weedleeedle** [AntoineGagne/cmus-notify#8]
I used the cmus_notify.sh script given in the readme:
`cmus_notify --title "Now playing: {title} by {artist}" --body "<b>Album:</b> {album}\n<b>Duration:</b> {duration}" "$*" &`

My work around was just putting an actual new line in the body tag as follows:
`cmus_notify --title "Now playing: {title} by {artist}" --body "<b>Album:</b> {album}
<b>Duration:</b> {duration}" "$*" &`

**Comment by AntoineGagne** [comment]
Thank you for reporting the problem! Unfortunately, shell scripts don't seem to support newlines. There are three workaround: to do as you did, to use an heredoc or to use `printf`. I'll update the readme to fix this error.

For the time being, in case you are interested in the other two methods:

Heredoc:

```sh
_body=$(cat << EOF
<b>Album:</b> {album}
<b>Duration:</b> {duration}
EOF
)

cmus_notify --title "Now playing: {title} by {artist}" --body "${_body}" "$*" &
```

`printf`:

```sh
cmus_notify --title "Now playing: {title} by {artist}" --body "$(printf "<b>Album:</b> {album}\n<b>Duration:</b> {duration}")" "$*" &
```
