### ISSUE TITLE
{artist} tag returns "(track artist) albumartist <album artist>"

### ISSUE THREAD

**Issue by weedleeedle** [AntoineGagne/cmus-notify#9]
Would there be anyway to get the {artist} tag to just return the track artist instead of the big ugly "(track artist) albumartist <album artist>". Or even better, split it up so that there is an {artist} tag and and {albumartist} tag or something like that?

**Comment by AntoineGagne** [comment]
It's probably an error in the parser since I didn't know that there was an `albumartist` field. I'll update the parser to consider this case.
